### ISSUE TITLE
Client connecting to server ERROR

### ISSUE THREAD

**Issue by flusity** [Yomalex/MuEmu#12]
Hello, I can't connect to the client at all, the server I chose is Season17Kor and the client game version is taken from the link you provided.

https://www.mediafire.com/file/g91or6xhbuf47jt/MuClient_S17_v1.19.74.7z/file

The server seems to have started properly:
![cmdw](https://github.com/user-attachments/assets/6a116a92-83f3-4d60-9076-aa9e46770b8d)

I also add my settings in the files:
**Server.xml**
`<Name>GameServer</Name>
  <Code>0</Code>
  <Show>1</Show>
  <Lang>en</Lang>
  <AutoRegister>true</AutoRegister>
  <Season>Season17Kor</Season>
  <Connection>
    <IP>127.0.0.1</IP>
    <IPPublic>127.0.0.1</IPPublic>
    <Port>55901</Port>
    <ConnectServerIP>127.0.0.1</ConnectServerIP>
    <APIKey>api-2020110116</APIKey>
  </Connection>
  <Database>
    <DBIp>127.0.0.1</DBIp>
    <DataBase>muonline2</DataBase>
    <BDUser>root</BDUser>
    <DBPassword>*************</DBPassword>
  </Database>
  <Client>
    <Version>11974</Version>
    <Serial>fughy683dfu7teqg</Serial>
    <CashShopVersion>512.2014.124</CashShopVersion>
  </Client>
  <GamePlay>
    <Experience>10</Experience>
    <GoldExperience>10</GoldExperience>
    <Zen>10</Zen>
    <DropRate>60</DropRate>
    <MaxPartyLevelDifference>400</MaxPartyLevelDifference>
    <PVP>true</PVP>
  </GamePlay>`

**ServerinfoDto.cs**

` 
namespace MuEmu.Resources.XML
{
    [XmlType(AnonymousType = true)]
    [XmlRoot("Server")]
    public class ServerInfoDto
    {
        [XmlElement] public string Name { get; set; } = "GameServer";
        [XmlElement] public int Code { get; set; } = 0;
        [XmlElement] public int Show { get; set; } = 1;
        [XmlElement] public string Lang { get; set; } = "en";
        [XmlElement] public bool AutoRegister { get; set; } = true;
        [XmlElement] public ServerSeason Season { get; set; } = ServerSeason.Season17Kor;

        [XmlElement("Connection")] public ConnectionInfoDto Connection { get; set; } = new ConnectionInfoDto();
        [XmlElement("Database")] public DatabaseInfoDto Database { get; set; } = new DatabaseInfoDto();
        [XmlElement("Client")] public ClientInfoDto Client { get; set; } = new ClientInfoDto();
        [XmlElement("GamePlay")] public GamePlayInfoDto GamePlay { get; set; } = new GamePlayInfoDto();
        [XmlElement("Files")] public FilesInfoDto Files { get; set; } = new FilesInfoDto();
        [XmlElement("Event")] public EventDto[] Events { get; set; } = Array.Empty<EventDto>();
    }

    [XmlType(AnonymousType = true)]
    public class ConnectionInfoDto
    {
        [XmlElement] public string IP { get; set; } = "127.0.0.1";
        [XmlElement] public string IPPublic { get; set; } = "127.0.0.1";
        [XmlElement] public int Port { get; set; } = 55901;
        [XmlElement] public string ConnectServerIP { get; set; } = "127.0.0.1";
        [XmlElement] public string APIKey { get; set; } = "api-2020110116";
    }

    [XmlType(AnonymousType = true)]
    public class DatabaseInfoDto
    {
        [XmlElement] public string DBIp { get; set; } = "127.0.0.1";
        [XmlElement] public string DataBase { get; set; } = "muonline2";
        [XmlElement] public string BDUser { get; set; } = "root";
        [XmlElement] public string DBPassword { get; set; } = "***********";
    }

    [XmlType(AnonymousType = true)]
    public class ClientInfoDto
    {
        [XmlElement] public string Version { get; set; } = "11974";
        [XmlElement] public string Serial { get; set; } = "fughy683dfu7teqg";
        [XmlElement] public string CashShopVersion { get; set; } = "512.2014.124";
    }
`
**File CsConfigDto.cs**

`  <apiKey>api-2020110116</apiKey>
  <IP>127.0.0.1</IP>
  <IPChat>127.0.0.1</IPChat>
  <DataBase>
    <IP>127.0.0.1</IP>
    <Name>muonline2</Name>
    <User>root</User>
    <Password>**************</Password>
  </DataBase>
</ConnectServer>
`

**File: ClientConfig / config_1.19.74.0.ini**
`[LOGIN]
Version=1.19.74

[Option]
FTP_URL=*********// My IP
FTP_PORT=22

[MU]
Version=11975
URL = 192.168.1.110
Serial = fughy683dfu7teqg
Port = 44405
Console = 0
Log = 1`

**And MapServer.xml** 

`<MapServer>
  <Group>
      <GameServer Code="0" IP="192.168.1.110" Port="55901" Default="1">
          
      </GameServer>
      <GameServer Code="19" IP="192.168.1.110" Port="55919" Default="0">
          <Map ID="ValleyofLoren" MoveAbleOption="1" Dest="-1"/>
          <Map ID="LandofTrial" MoveAbleOption="1" Dest="-1"/>
          <Map ID="Crywolf" MoveAbleOption="1" Dest="-1"/>
          <Map ID="BarracksofBalgass" MoveAbleOption="1" Dest="-1"/>
          <Map ID="BalgassRefuge" MoveAbleOption="1" Dest="-1"/>
      </GameServer>
  </Group>
</MapServer>`

**configuration.xml**

`  <IP>127.0.0.1</IP>
  <IPChat>127.0.0.1</IPChat>
  <DataBase>
    <IP>127.0.0.1</IP>
    <Name>muonline2</Name>
    <User>root</User>
    <Password>**************</Password>
  </DataBase>`

**And client  config.ini** 

`[LOGIN]
Version=1.19.74

[Option]
FTP_URL=************
FTP_PORT=22

[MU]
Version=11975
URL = 192.168.1.110
Serial = fughy683dfu7teqg
Port = 44405
Console = 0
Log = 1
`
**The resulting result is:**

![gmloading](https://github.com/user-attachments/assets/41f3e236-55b3-4713-9cd2-7c7d0767ebef)

_And an error is received_

![gmfolder](https://github.com/user-attachments/assets/8f21192e-5f4c-42da-a579-95f321cdd548)

What is wrong or what did I miss?

Thanks in advance for your reply.

**Comment by flusity** [comment]
Hello,

Sorry to bother you with this question, but in order to further explore and test your server, I would like to know how to connect with the game client. I tried to change the GameServer IP address on the server but failed. I'm also considering editing the main.exe file using Hex, but I don't know exactly what needs to be changed.

I would greatly appreciate it if you could explain how to properly connect the game client to your server. I have read all the available information in your project but I still can't find the solution.

**Thank you for your help!**

**Comment by Yomalex** [comment]
The client needs to have the dll that comes with the project (MUConnector) attached, you have to compile it and configure it with the config.ini (https://github.com/Yomalex/MuEmu/tree/master/ClientConfig) available according to the version loaded in this repository

This dll overwrites main.dll originally included in the client
S17 client version supported by the server is available on Discord, 1.19.74 is unsupported

From discord:
Season 17: 
Base Client
https://mega.nz/file/XN1yXaJY#kLGneYNVTrtiDjIMAXHAaNPkOAV1nf8kLprXk89wV5w
Patch for S17 Version
https://mega.nz/file/eVFEFT6J#gamAQXVeYLeO0yD-znGJP2M3bZ-VB7QGSFTNfwutWfk

**Comment by flusity** [comment]
Hello,

Thanks for the information provided.
Could you please explain in more detail the steps involved in compiling this file? What environments and tools are required to properly prepare MUConnector?
Maybe you can ask for the steps, I would really appreciate it.

Thank you very much for your help!

**Comment by Yomalex** [comment]
Hello,

You need to use Visual Studio with C++ dev tools in Release compilation mode

**Comment by flusity** [comment]
Hello, I'm very sorry that maybe I don't have enough knowledge, but I should understand in more detail. there is no main.dll in the client and patch files, I run tools, but you should know what needs to be done to generate or overwrite the main.dll ur where to find it when it is generated. Please help to solve this problem if you can.
config.ini i set by my internal IP 

![tools](https://github.com/user-attachments/assets/83802d5b-f58c-4110-bd3d-5256305b0263)

**Comment by Yomalex** [comment]
Hello, this project is in developement with multiple bugs and errors, and the issues section is not for questions, this is not a forum.
If you need help of how run this project please use the Discord Channel.
