### ISSUE TITLE
Status.

### ISSUE THREAD

**Issue by juliolitwin** [Yomalex/MuEmu#3]
Yo,

How is the project's progress status currently? Can you update the discord invitation?

**Comment by Yomalex** [comment]
The project is in develop working partially.
Non working yet:
Events like: Kanturu Refinery, DopplerGanger, Illusion Temple, Castle Siege, Selupan, MuRummy, Fortress of Imperial Guardian, BattleCore.
World Quest from NPC.
Quest Balgass Refuge (For Lv3)

I will update discord Invitation, thx
