### ISSUE TITLE
Where can season 17 be downloaded

### ISSUE THREAD

**Issue by wuliao6688** [Yomalex/MuEmu#4]
Where can season 16  or season 17  be downloaded

**Comment by Yomalex** [comment]
From WebZen Web Page, but S17 is not fully supported jet by this server, only works for login screen
Client S16 
https://www.mediafire.com/file/xtog58uk86js9qw/Client_-_LgdMu_S16_1.1.zip/file
Client S17 1.19.74
https://www.mediafire.com/file/g91or6xhbuf47jt/MuClient_S17_v1.19.74.7z/file
