### ISSUE TITLE
How to start game Client?

### ISSUE THREAD

**Issue by sandunban** [Yomalex/MuEmu#7]
thank’s for you share the Emulator Code.
I'm very like MuOnline ,that since 20 years ago.
I fork the Emulator ,then buid it successfuly.
I run  CSEmu.exe  and  MuEmu.exe ,use 127.0.0.1 ，everything is OK . 

the CSEmu.exe terminal show 
`[Information WZServer] Started on TCP-IP:"127.0.0.1" TCP-PORT:44405`
`[Information WZServer] Started on TCP-IP:"127.0.0.1" TCP-PORT:55980`
`[Information WZServer] New Client added at index 1`
`[Information ServerManager] New server found [0]"GameServer" "NoPVP" "127.0.0.1":55901 "SHOW"`
`[Information MainServices] Sending Server list 1 servers`

the MuEmu.exe terminal show

`12:20:09 [Information ChaosCastle 1][:] Estatus:Closed->Open`
`12:20:09 [Information ChaosCastle 2][:] Estatus:Closed->Open`
`12:20:09 [Information ChaosCastle 3][:] Estatus:Closed->Open`
`12:20:09 [Information ChaosCastle 4][:] Estatus:Closed->Open`
`12:20:09 [Information ChaosCastle 5][:] Estatus:Closed->Open`
`12:20:09 [Information ChaosCastle 6][:] Estatus:Closed->Open`
`12:20:09 [Information ChaosCastle 7][:] Estatus:Closed->Open`
`12:20:09 [Information Crywolf][:] Estatus:Closed->None`
`12:20:09 [Information MoonRabbit][:] Estatus:Open->Playing`
`12:20:09 [Information ][:] Anuncio a mapas sin evento: [Moon Rabbit] Lunar Rabits invadieron Elbeland`
`12:20:09 [Information WhiteWizard][:] Estatus:Open->Playing`
`12:20:09 [Information WhiteWizard][:] Started in 168,165`
`12:20:09 [Information ][:] Anuncio Global:The White Wizard and his corps has invaded Noria`
`12:20:09 [Information CastleSiegeState][:] Estatus:None->Idle1`
`12:20:09 [Information CastleSiegeState][:] Sync State: Idle1, NextState RegisteSiege at 06/28/2023 12:20:09`
`12:20:10 [Information CastleSiegeState][:] Estatus:Idle1->RegisteSiege`
`12:20:10 [Information CastleSiegeState][:] Sync State: RegisteSiege, NextState Idle2 at 06/30/2023 12:19:10`
`12:20:11 [Information KanturuStandBy][:] Estatus:None->Start`
`12:21:08 [Information SubSystem][:] Saving players`
`12:21:08 [Information SubSystem][:] Saved players`
`12:21:08 [Information AcheronGuardian][:] Estatus:Open->Playing`
`12:21:08 [Information ][:] Anuncio a mapas sin evento: Acheron Guardian is Started!.`

Everything seems normal...

So,I need login the game ,  but I don't known how to open game .  I can't find Lancher .
I saw MU.Connector.project in the solution,  I build it then get Main.dll,Main.exp,Main.lib,Main.pdb.
I use the client is https://github.com/Yomalex/IGCN-v9.5-MuServer-S9EP2/tree/master/zClient
could you help me that How to login the game 

![MuEmustart](https://github.com/Yomalex/MuEmu/assets/22810815/0a68858e-a7b6-457b-a954-70ffe316111c)

**Comment by sandunban** [comment]
I  Copy Text From Config_1.5.25.0.ini  paste it to  zClient\Config.ini  , and modified URL to 127.0.0.1
also I modifid  IP  chartPort  and  Serial at  zClient\Data\Local\ServerInfo.bmd 
whether I start zClient\Mu.exe  or  MuResolutionSelector.exe  or Main.exe
In a few seconds ，the game window show  "You are disconnect form the server"  with olny OK button . 
click the button to exit the game.
I still haven't been able to enter the game。

**Comment by allanbatista** [comment]
@sandunban Hi. There exists best client that fit with that server?

**Comment by sandunban** [comment]
> @sandunban Hi. There exists best client that fit with that server?

Hello, the client I'm using is the "Client Season 9" mentioned in the first line of the ReadMe.md file. I think this should be the compatible client, right?
Can you enter the game?

**Comment by Yomalex** [comment]
Client S9 is an IGN client, you need rename Main.dll to IGC.dll and then replace in client side.
Mu Client can't use IP 127.0.0.1, you need put your Private IP

**Comment by flusity** [comment]
Copy Text From Config_1.5.25.0.ini paste it to zClient\Config.ini , and modified URL to 127.0.0.1 also I modifid IP chartPort and Serial at zClient\Data\Local\ServerInfo.bmd whether I start zClient\Mu.exe or MuResolutionSelector.exe or Main.exe In a few seconds ，the game window show "You are disconnect form the server" with olny OK button . click the button to exit the game. I still haven't been able to enter the game。

hello, I want to ask if you found a solution to connect to the game, I still can't connect at all, if you can share your experience, because the author is not responding to me for some reason.
